# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.build(); Pkg.test(; coverage=true)'

after_success:
  # push coverage to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("QRupdate")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

